# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7.42-debian
    container_name: db-mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    volumes:
      - ~/data/mysql:/var/lib/mysql
      - ./config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: moho
      MYSQL_PASSWORD: moho123

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

  app:
    image: awpp:1
    container_name: app
    privileged: true
    #restart: always

    volumes:
      - ~/app:/home/admin/web/public_html/public/

    environment:
      TERM: xterm

    ports:
      - 8080:8080

    command: apache2ctl -D FOREGROUND
