# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0-debian
    container_name: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    volumes:
      - ~/data/mysql8:/var/lib/mysql
      - ./config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: moho
      MYSQL_PASSWORD: moho123

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1

  app: 
    image: wordpress81:latest
    container_name: app
    privileged: true
    #restart: always

    volumes:
      - ./src:/home/admin/web/public_html/public/
      - ./config/apache/php.ini:/etc/php/8.1/apache2/php.ini

    environment:
      TERM: xterm

    ports:
      - 8080:8080

    command: apache2ctl -D FOREGROUND
